USE ROLE USERADMIN;
CREATE ROLE DATA_ENGINEER;
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE DATABASE WS_DEMO_DB;
GRANT OWNERSHIP ON DATABASE WS_DEMO_DB TO ROLE DATA_ENGINEER;

CREATE WAREHOUSE DATA_ENGINEER_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE DATA_ENGINEER_WH TO ROLE DATA_ENGINEER;

USE ROLE DATA_ENGINEER;
CREATE SCHEMA WS_DEMO_DB.BRONZE;
CREATE SCHEMA WS_DEMO_DB.SILVER;
CREATE SCHEMA WS_DEMO_DB.GOLD;

